### ISSUE TITLE
Update Maven deployment Action

### ISSUE THREAD

**Issue by xomiamoore** [vanillabp/camunda7-adapter#23]
Hello! We had to make a few changes to our community's Maven deployment Action. Specifically, we updated the secret names and deployment credentials.

Please update to [the latest release, v. 1.2.1](https://github.com/camunda-community-hub/community-action-maven-release/releases/tag/v1.2.1), to make sure your Action works. Thank you!

**Comment by stephanpelikan** [comment]
Updated with release [v1.2.1](https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/releases/tag/1.2.1).
