### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by stephanpelikan** [vanillabp/camunda7-adapter#4]
Hi,

@camunda-community-hub/devrel:

I want to get a new release published. Upfront before the first release there were some problems, also regarding the GPG secrets (https://github.com/camunda-community-hub/community/issues/62#issuecomment-1398953610). Unfortunately, the secrets are gone! Also for the related project https://github.com/camunda-community-hub/vanillabp-camunda8-adapter.

This is the reason why the action for this release failed: https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/actions/runs/4023024758

Can you please fix this (also for the second project), rerun my action and publish the release afterwards. Please keep in mind to make a permanent fix for this because we use this in customer projects and we need to create releases in a reliable way.

@NPDeehan: You helped last time. Thank you for this. Can you tell me if someone of the community-hub team is also from Europe, so I can expect responses also during European daytime or are all members of this team located in US?

Thx, Stephan

**Comment by stephanpelikan** [comment]
@camunda-community-hub/devrel: Beside that current problem (GPG): Why the stage is not automatically published to Maven-Central? Why always this manual step of asking for publishing the release is necessary? My current expirience is that this slows down - especially until this extension is out of the incubating phase.

**Comment by berndruecker** [comment]
Hi @stephanpelikan - I saw your escalation via Stephan. I am not sure how we generally handle the credentials but can check in with @xomiamoore later. For now I added those credentials manually to both projects.

**Comment by berndruecker** [comment]
@stephanpelikan Hang on - can it be that you did not properly onboard your repo like described here: https://github.com/camunda-community-hub/infrastructure/#use-case-onboarding-a-new-community-hub-repository - seems like your repo is not within the list of onboarded repo (which I think is used by Terraform to add credentials - which means manual changes are overwritten)

**Comment by berndruecker** [comment]
Onboarded repo properly: https://github.com/camunda-community-hub/infrastructure/pull/53

**Comment by stephanpelikan** [comment]
This is not something I should have done!?

**Comment by berndruecker** [comment]
That PR is actually part of the onboarding of Community Extensions - but I double checked and this is either gone from the documentation or more likely pretty hidden - @xomiamoore - could you create the appropriate issue to sort this out? I know we had this very front of docs once but have not found it linked any more.

**Comment by stephanpelikan** [comment]
Ok I found it in https://github.com/camunda-community-hub/community/blob/29a9a6a3ba11db474f304b2288de7b4486f3066e/RELEASE.MD - the first bullet-point. I didn't get that this is a another issue. I thought one would be good. Should I follow that right now?

**Comment by berndruecker** [comment]
I created that PR and approved it for you - so that should be good already

**Comment by berndruecker** [comment]
I created https://github.com/camunda-community-hub/community-action-maven-release/issues/48 for the auto release of artifacts pushed to Maven Central. This was discussed a couple of times in the past - but I am not sure what the latest state of discussion was. But I agree that it is pretty inconvenient for everybody involved to have a manual step forced in here.

**Comment by stephanpelikan** [comment]
Did you also adopt the configuration for the sister-project vanillabp-camunda8-adapter ?

The current action gives me this error:
```
Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (default-deploy) on project camunda7-spring-boot-adapter: Failed to deploy artifacts: Could not transfer artifact org.camunda.community.vanillabp:camunda7-spring-boot-adapter:jar:1.0.2 from/to central (https://oss.sonatype.org//service/local/staging/deploy/maven2/): transfer failed for https://oss.sonatype.org//service/local/staging/deploy/maven2/org/camunda/community/vanillabp/camunda7-spring-boot-adapter/1.0.2/camunda7-spring-boot-adapter-1.0.2.jar, status: 504 Gateway Time-out -> [Help 1]
```

(see https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/actions/runs/4023024758/jobs/6952230722)

**Comment by berndruecker** [comment]
I saw it - this is kind of related to what other community users saw earlier today (https://github.com/camunda-community-hub/zeebe-redis-exporter/issues/5) - I wonder if that is some network hiccup on the Sonatype site - as I have never seen this so far and also have no idea what to do about it. But I can open an issue with SOnatype

**Comment by berndruecker** [comment]
And yes, `vanillabp-camunda8-adapter` got also onboarded properly

**Comment by berndruecker** [comment]
I also get it on the Sonatype UI - so I think some propblem on their side - sorry
![grafik](https://user-images.githubusercontent.com/1217596/215468002-0d816a98-afdb-45c1-9617-0152bb5a0d31.png)

**Comment by stephanpelikan** [comment]
hmm. I think we need to wait? 

by-the-way: thank you for supporting me 👍 and sorry, that I also missed something to configure 👎

**Comment by berndruecker** [comment]
Created https://issues.sonatype.org/browse/MVNCENTRAL-7816 - I have no other ideas than waiting at the moment :-(

**Comment by berndruecker** [comment]
> seems like Sonatype has some challenges with "unexpected" workload, we're not the only ones having issues since the last weekend. See e.g. https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-8825.

**Comment by berndruecker** [comment]
https://issues.sonatype.org/browse/MVNCENTRAL-7816:
> Sorry for the late reply, but oss.sonatype.org was clearly not able to keep up with the extraordinary load it experienced this morning and also late last week.  We completed a maintenance window to apply configuration updates that seem to have restored performance, but we will continue to monitor activity on the host.

I restarted the release action, 🤞

**Comment by berndruecker** [comment]
Published successfully - and I also released it to Maven Central @stephanpelikan

**Comment by berndruecker** [comment]
I close this for now @stephanpelikan - let me know if you object. The auto-release will be followed up in https://github.com/camunda-community-hub/community-action-maven-release/issues/48, so there is nothing left to do here, right?

**Comment by stephanpelikan** [comment]
Thank you, yes everything is fine now! I hope next time it will be more smooth 😄. I'm always sorry to reach out but I try to avoid bringing internal problems to the customer. I'm also sorry, that this time it was caused by me missing to create this infrastructure issue.

**Comment by berndruecker** [comment]
No worries - every glitch is a great learning opportunity to see how we can improve onboarding experience or reduce your dependency on us. So never hesitate to reach out! 

Just Sonatype was bad luck 😬

**Comment by xomiamoore** [comment]
Thank you to @berndruecker for sorting this while I was out sick -- you're right, I want to take everything we've learned from this and improve the onboarding experience for everyone! So thank you for all the feedback @stephanpelikan and don't worry about reaching out too much :)
